con1 = set(range(22))
print(con1)
con2 = {7, 3, 21}
print(con2)

conjunto = con1.__dir__()
for func in conjunto:
    print(f'print(tupla.{func}())')

# print(tupla.__repr__())
# print(tupla.__hash__())
# print(tupla.__getattribute__())
# print(tupla.__lt__())
# print(tupla.__le__())
# print(tupla.__eq__())
# print(tupla.__ne__())
# print(tupla.__gt__())
# print(tupla.__ge__())
# print(tupla.__iter__())
# print(tupla.__init__())
# print(tupla.__sub__())
# print(tupla.__rsub__())
# print(tupla.__and__())
# print(tupla.__rand__())
# print(tupla.__xor__())
# print(tupla.__rxor__())
# print(tupla.__or__())
# print(tupla.__ror__())
# print(tupla.__isub__())
# print(tupla.__iand__())
# print(tupla.__ixor__())
# print(tupla.__ior__())
# print(tupla.__len__())
# print(tupla.__contains__())
# print(tupla.__new__())
# print(tupla.add())
# print(tupla.clear())
# print(tupla.copy())
# print(tupla.discard())
# print(tupla.difference())
# print(tupla.difference_update())
# print(tupla.intersection())
# print(tupla.intersection_update())
# print(tupla.isdisjoint())
# print(tupla.issubset())
# print(tupla.issuperset())
# print(tupla.pop())
# print(tupla.__reduce__())
# print(tupla.remove())
# print(tupla.__sizeof__())
# print(tupla.symmetric_difference())
# print(tupla.symmetric_difference_update())
# print(tupla.union())
# print(tupla.update())
# print(tupla.__doc__())
# print(tupla.__str__())
# print(tupla.__setattr__())
# print(tupla.__delattr__())
# print(tupla.__reduce_ex__())
# print(tupla.__subclasshook__())
# print(tupla.__init_subclass__())
# print(tupla.__format__())
# print(tupla.__dir__())
# print(tupla.__class__())
